const DISCIPLINES_DATA = [
  // ── Período 1 ──────────────────────────────────────────────────────────────
  { id:'fund-edu',   name:'Fundamentos da Educação',                     period:1, hours:60, order:0,
    teoria:{hours:60,nucleus:'I'},   pratica:{hours:0, nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DED',  color:'salmon', isElective:false, eadPercent:0 },
  { id:'psico-1',    name:'Psicologia I',                                period:1, hours:60, order:1,
    teoria:{hours:60,nucleus:'I'},   pratica:{hours:0, nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DED',  color:'salmon', isElective:false, eadPercent:0 },
  { id:'pens-comp',  name:'Pensamento Computacional',                    period:1, hours:60, order:2,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'blue',   isElective:false, eadPercent:0 },
  { id:'mat-disc-1', name:'Matemática Discreta I',                       period:1, hours:60, order:3,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'cyan',   isElective:false, eadPercent:0 },
  { id:'inf-soc',    name:'Informática e Sociedade',                     period:1, hours:60, order:4,
    teoria:{hours:0, nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:60,nucleus:'III'},
    prerequisites:[], department:'DC',   color:'purple', isElective:false, eadPercent:0 },

  // ── Período 2 ──────────────────────────────────────────────────────────────
  { id:'ed-bra',     name:'Educação Brasileira: legislação, organização e políticas', period:2, hours:60, order:0,
    teoria:{hours:60,nucleus:'I'},   pratica:{hours:0, nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DED',  color:'salmon', isElective:false, eadPercent:0 },
  { id:'psico-2',    name:'Psicologia II',                               period:2, hours:60, order:1,
    teoria:{hours:60,nucleus:'I'},   pratica:{hours:0, nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:['psico-1'], department:'DED', color:'salmon', isElective:false, eadPercent:0 },
  { id:'prog-1',     name:'Programação I',                               period:2, hours:60, order:2,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['pens-comp'], department:'DC', color:'blue', isElective:false, eadPercent:0 },
  { id:'mat-disc-2', name:'Matemática Discreta II',                      period:2, hours:60, order:3,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['mat-disc-1'], department:'DC', color:'cyan', isElective:false, eadPercent:0 },
  { id:'calc-1',     name:'Cálculo NI',                                  period:2, hours:60, order:4,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DM',   color:'green',  isElective:false, eadPercent:0 },

  // ── Período 3 ──────────────────────────────────────────────────────────────
  { id:'didatica',   name:'Didática',                                    period:3, hours:60, order:0,
    teoria:{hours:30,nucleus:'I'},   pratica:{hours:30,nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DED',  color:'salmon', isElective:false, eadPercent:0 },
  { id:'ihm',        name:'Interação Homem-Máquina',                     period:3, hours:60, order:1,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'blue',   isElective:false, eadPercent:0 },
  { id:'prog-2',     name:'Programação II',                              period:3, hours:60, order:2,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['prog-1'], department:'DC', color:'blue', isElective:false, eadPercent:0 },
  { id:'teoria-comp',name:'Teoria da Computação',                        period:3, hours:60, order:3,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['mat-disc-2'], department:'DC', color:'cyan', isElective:false, eadPercent:0 },
  { id:'calc-2',     name:'Cálculo NII',                                 period:3, hours:60, order:4,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DM',   color:'green',  isElective:false, eadPercent:0 },

  // ── Período 4 ──────────────────────────────────────────────────────────────
  { id:'met-ens',    name:'Metodologia do Ensino da Computação',         period:4, hours:60, order:0,
    teoria:{hours:30,nucleus:'I'},   pratica:{hours:30,nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:['didatica'], department:'DED', color:'salmon', isElective:false, eadPercent:0 },
  { id:'aed',        name:'Algoritmos e Estruturas de Dados',            period:4, hours:60, order:1,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['mat-disc-1','prog-1'], department:'DC', color:'blue', isElective:false, eadPercent:0 },
  { id:'circ-dig',   name:'Circuitos Digitais',                          period:4, hours:60, order:2,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'blue',   isElective:false, eadPercent:0 },
  { id:'estat',      name:'Estatística Exploratória',                    period:4, hours:60, order:3,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'cyan',   isElective:false, eadPercent:0 },
  { id:'alg-lin',    name:'Álgebra Linear NI',                           period:4, hours:60, order:4,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DM',   color:'green',  isElective:false, eadPercent:0 },

  // ── Período 5 ──────────────────────────────────────────────────────────────
  { id:'erer',       name:'Educ. das Relações Étnico-Raciais',           period:5, hours:60, order:0,
    teoria:{hours:60,nucleus:'I'},   pratica:{hours:0, nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DLCH', color:'salmon', isElective:false, eadPercent:0 },
  { id:'eso-1',      name:'Estágio Supervisionado Obrigatório I',        period:5, hours:90, order:1,
    teoria:{hours:0, nucleus:'IV'},  pratica:{hours:90,nucleus:'IV'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['ed-bra','met-ens'], department:'DC', color:'orange', isElective:false, eadPercent:0, skipWeekly:true },
  { id:'arq-comp',   name:'Arquitetura de Computadores',                 period:5, hours:60, order:2,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['circ-dig','aed'], department:'DC', color:'blue', isElective:false, eadPercent:0 },
  { id:'bd',         name:'Banco de Dados',                              period:5, hours:60, order:3,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['aed'], department:'DC', color:'blue', isElective:false, eadPercent:0 },
  { id:'redes',      name:'Redes de Computadores',                       period:5, hours:60, order:4,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['prog-2'], department:'DC', color:'blue', isElective:false, eadPercent:0 },

  // ── Período 6 ──────────────────────────────────────────────────────────────
  { id:'libras',     name:'Língua Brasileira de Sinais – Libras',        period:6, hours:60, order:0,
    teoria:{hours:60,nucleus:'I'},   pratica:{hours:0, nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DL',   color:'salmon', isElective:false, eadPercent:0 },
  { id:'eso-2',      name:'Estágio Supervisionado Obrigatório II',       period:6, hours:90, order:1,
    teoria:{hours:0, nucleus:'IV'},  pratica:{hours:90,nucleus:'IV'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['eso-1'], department:'DC', color:'orange', isElective:false, eadPercent:0, skipWeekly:true },
  { id:'tec-edu',    name:'Tecnologias na Educação',                     period:6, hours:60, order:2,
    teoria:{hours:20,nucleus:'II'},  pratica:{hours:20,nucleus:'II'}, extensao:{hours:20,nucleus:'III'},
    prerequisites:['prog-2'], department:'DC', color:'purple', isElective:false, eadPercent:0 },
  { id:'es',         name:'Engenharia de Software',                      period:6, hours:60, order:3,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['prog-2'], department:'DC', color:'blue',   isElective:false, eadPercent:0 },
  { id:'ia',         name:'Inteligência Artificial',                     period:6, hours:60, order:4,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['prog-2'], department:'DC', color:'blue',   isElective:false, eadPercent:0 },

  // ── Período 7 ──────────────────────────────────────────────────────────────
  { id:'prod-tex',   name:'Produção de Textos Acadêmicos I',             period:7, hours:60, order:0,
    teoria:{hours:60,nucleus:'I'},   pratica:{hours:0, nucleus:'I'},  extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DL',   color:'salmon', isElective:false, eadPercent:0 },
  { id:'eso-3',      name:'Estágio Supervisionado Obrigatório III',      period:7, hours:90, order:1,
    teoria:{hours:0, nucleus:'IV'},  pratica:{hours:90,nucleus:'IV'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['eso-2'], department:'DC', color:'orange', isElective:false, eadPercent:0, skipWeekly:true },
  { id:'proj-1',     name:'Projeto Integrador em Desenv. de Software I', period:7, hours:120, order:2,
    teoria:{hours:0, nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:120,nucleus:'III'},
    prerequisites:['es'], department:'DC', color:'purple', isElective:false, eadPercent:0 },
  { id:'so',         name:'Sistemas Operacionais',                       period:7, hours:60, order:3,
    teoria:{hours:30,nucleus:'II'},  pratica:{hours:30,nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['circ-dig','aed'], department:'DC', color:'blue', isElective:false, eadPercent:0 },
  { id:'opt-1',      name:'Optativa 1',                                  period:7, hours:60, order:4,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'gray',   isElective:true,  eadPercent:0 },

  // ── Período 8 ──────────────────────────────────────────────────────────────
  { id:'met-cient',  name:'Metodologia Científica Aplicada à Computação',period:8, hours:60, order:0,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'blue',   isElective:false, eadPercent:0 },
  { id:'eso-4',      name:'Estágio Supervisionado Obrigatório IV',       period:8, hours:135, order:1,
    teoria:{hours:0, nucleus:'IV'},  pratica:{hours:135,nucleus:'IV'},extensao:{hours:0, nucleus:'III'},
    prerequisites:['eso-3'], department:'DC', color:'orange', isElective:false, eadPercent:0, skipWeekly:true },
  { id:'proj-2',     name:'Projeto Integrador em Desenv. de Software II',period:8, hours:120, order:2,
    teoria:{hours:0, nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:120,nucleus:'III'},
    prerequisites:['proj-1'], department:'DC', color:'purple', isElective:false, eadPercent:0 },
  { id:'opt-2',      name:'Optativa 2',                                  period:8, hours:60, order:3,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'gray',   isElective:true,  eadPercent:0 },

  // ── Período 9 ──────────────────────────────────────────────────────────────
  { id:'tcc',        name:'Trabalho de Conclusão de Curso — TCC',        period:9, hours:120, order:0,
    teoria:{hours:120,nucleus:'II'}, pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:['met-cient'], department:'DC', color:'blue',   isElective:false, eadPercent:0, skipWeekly:true },
  { id:'opt-3',      name:'Optativa 3',                                  period:9, hours:60, order:1,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'gray',   isElective:true,  eadPercent:0 },
  { id:'opt-4',      name:'Optativa 4',                                  period:9, hours:60, order:2,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'gray',   isElective:true,  eadPercent:0 },
  { id:'opt-5',      name:'Optativa 5',                                  period:9, hours:60, order:3,
    teoria:{hours:60,nucleus:'II'},  pratica:{hours:0, nucleus:'II'}, extensao:{hours:0, nucleus:'III'},
    prerequisites:[], department:'DC',   color:'gray',   isElective:true,  eadPercent:0 },
]
